// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv7b0P1ma39wrfoOsL0KTRxJ1rVyH5MZc',
    appId: '1:117205480809:web:b5acf71c575d72ccf8f9f8',
    messagingSenderId: '117205480809',
    projectId: 'e-comm-d12e1',
    authDomain: 'e-comm-d12e1.firebaseapp.com',
    storageBucket: 'e-comm-d12e1.appspot.com',
    measurementId: 'G-CX9BZ71PBE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVBXS6wgLOxgI_KUaVRtdU_8bbeW7bomo',
    appId: '1:117205480809:android:82f61d048a382bdef8f9f8',
    messagingSenderId: '117205480809',
    projectId: 'e-comm-d12e1',
    storageBucket: 'e-comm-d12e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWa1yBTvjV70G7VnzgptNOxFr51fmlyBs',
    appId: '1:117205480809:ios:cbd31bcbca47ae23f8f9f8',
    messagingSenderId: '117205480809',
    projectId: 'e-comm-d12e1',
    storageBucket: 'e-comm-d12e1.appspot.com',
    iosBundleId: 'com.zeedevs.adminPanelEcom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWa1yBTvjV70G7VnzgptNOxFr51fmlyBs',
    appId: '1:117205480809:ios:4addad604836fc52f8f9f8',
    messagingSenderId: '117205480809',
    projectId: 'e-comm-d12e1',
    storageBucket: 'e-comm-d12e1.appspot.com',
    iosBundleId: 'com.zeedevs.adminPanelEcom.RunnerTests',
  );
}
